#! /bin/bash

ACCOUNT=wainwright.ja
GMAIL="https://mail.google.com/mail/u/0/#inbox"
READER="http://www.google.co.uk/reader/?hl=en&tab=yy"
#curl -u $ACCOUNT:Zaphod42[] --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n "s/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2 - \1/p"> /tmp/mail.txt

curl -u wainwright.ja:Zaphod42[] --silent "https://mail.google.com/mail/feed/atom" | perl -ne 'print "\t" if /<name>/; print "$2\n" if /<(title|name)>(.*)<\/\1>/;' > /tmp/mail.txt

ACTION=$(yad --text-info --title="Unread Messages" \
		--width=500 --height=300 \
		--filename=/tmp/mail.txt \
		--button="Gmail:2" \
		--button="Reader:4" \
		--button=gtk-ok:0)
ret=$?

[[ $ret -eq 1 ]] && exit 0

if [[ $ret -eq 2 ]]; then
    xdg-open $GMAIL &
  exit 0
elif [[ $ret -eq 4 ]]; then
    xdg-open $READER &
  exit 0
fi
